### ISSUE TITLE
Can I use sd in Mineclone 2

### ISSUE THREAD

**Issue by simondueckert** [Kilarin/simple_dialogs#2]
I have a minetest server running with the Mineclone 2 game. There are already NPCs implemented but I do not know which mod that is. Does anybody know, if it's possible to enable simple dialogs in Mineclone 2?

**Comment by Kilarin** [comment]
Hello!  
it appears to me that mineclone 2 has a custom npc mod?   It should not be difficult to add simple_dialogs to it by modifying that mod as detailed in the readme.
